version: '3.2'
services:
  spring-boot:
    build:
      context: .
    volumes:
      - type: bind
        source: src
        target: /app/src
    ports:
      - "8084:80"
    environment:
      - PORT=80