openapi: 3.0.0
info:
  title: Wallet Account User Service
  version: 0.0.1
  description: |
    Wallet Account User Service is a REST HTTP API for managing user data.
    User Kyc level and kyc documents are handled by a different service
  termsOfService: 'http://swagger.io/terms/'
  x-logo:
    url: 'https://redocly.github.io/redoc/petstore-logo.png'
    backgroundColor: '#FFFFFF'
    altText: Petstore logo
servers:
  - url: 'https://wallet-account-user-svc-uzqgb7lfiq-ew.a.run.app'
    description: Testing Server
tags:
  - name: Wallet Account Users
    description: Wallet Account Users are used to handle wallet operations on user data
    externalDocs:
      url: 'https://wallet-gateway-svc-uzqgb7lfiq-ew.a.run.app'
paths:
  /v1/users:
    get:
      summary: Obtain a list of wallet account users
      tags:
        - Wallet Account Users
      responses:
        '200':
          description: Successfully obtained the list of wallet account users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletAccountUsers'
    post:
      summary: Create a Wallet Account User
      tags:
        - Wallet Account Users
      requestBody:
        description: The wallet account user specification
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletAccountUser'
      responses:
        '201':
          description: Successfully created a wallet account user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletAccountUser'
  /v1/users/{userId}:
    get:
      summary: Fetch user data
      tags: 
       - Wallet Account Users
      parameters: 
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: 6784bbea-ea94-426e-bb64-594eeee6cb03
      responses:
        '201':
          description: Successfully created a wallet account user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletAccountUser'
    patch:
      summary: Update a Wallet Account User
      tags:
        - Wallet Account Users
      parameters: 
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: 6784bbea-ea94-426e-bb64-594eeee6cb03
      requestBody:
        description: The wallet account user specification
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletAccountUser'
      responses:
        '201':
          description: Successfully created a wallet account user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletAccountUser'
  
components:
  schemas:
    Address:
      type: object
      properties:
        streetName:
          type: string
        streetNumber:
          type: string
        city:
          type: string
        zipCode:
          type: string
        state:
          type: string
        country:
          type: string
    WalletAccountUser:
      type: object
      properties:
        id:
          type: string
          description: The user identifier
        lastName:
          type: string
          description: User last name
        firstName:
          type: string
          description: User first name
        address:
          $ref: '#/components/schemas/Address'
          description: User address
        email:
          type: string
          description: user email address
        phoneNumber:
          type: string
          description: User phone number
          example: '+33613047943'
    WalletAccountUsers:
      type: array
      items:
        $ref: '#/components/schemas/WalletAccountUser'
